#spring:
#  jpa:
#    database: mysql
#    show-sql: true
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        type: trace

multitenancy:
  mtapp:
    master:
      datasource:
        # url: jdbc:mysql://localhost:3306/master_db?useSSL=false
        # url: jdbc:mariadb://localhost:3306/master_db
        url: jdbc:postgresql://localhost:5432/master_db
        # username: root
        username: jean
        password: Anhnh7383@
        driverClassName: org.postgresql.Driver
        connectionTimeout: 20000
        maxPoolSize: 250
        idleTimeout: 300000
        minIdle: 5
        poolName: masterdb-connection-pool